apiVersion: v1
kind: Pod
metadata:
  name: opencloudcx-app
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=git://github.com/OpenCloudCX/opencloudcx-app"
    - "--destination=ajnriva/opencloudcx-app:1.0"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: ajnriva-cred
      items:
        - key: .dockerconfigjson
          path: config.json
